base generator implementation
rispa-io/rispa-generator pull request #1
Opened 2017-05-28 09:49 UTC by Fyzu

2017-05-28 09:49 UTC, Fyzu commented
![](https://github.trello.services/images/mini-trello-icon.png) [22 Вынести в отдельный пакет generator](https://trello.com/c/2M0tZJD3/22-22-generator)

2017-05-28 15:14 UTC, Laiff requested changes

2017-05-28 15:14 UTC, Laiff commented on src/generators/project/.gitignore.hbs
> +.idea/
Добавь сюда еще .vscode он набирает популярность в последнее время

2017-05-29 08:31 UTC, Fyzu commented on src/generators/project/.gitignore.hbs
> +.idea/
Это да. Сам его использую Х)

2017-05-29 08:51 UTC, Laiff approved these changes

2017-05-29 08:52 UTC, merged